apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onlyoffice.fullname" . }}-config
  labels:
    {{- include "onlyoffice.labels" . | nindent 4 }}
data:
  local-production-linux.json: |
    {{- dict "wopi" (dict "host" .Values.url) | toPrettyJson | nindent 4 }}
