apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-list-role
  namespace: nextcloud
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

