apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud-pods-list-binding
  namespace: nextcloud
subjects:
- kind: ServiceAccount
  name: default
  namespace: nextcloud
roleRef:
  kind: Role
  name: pods-list-role
  apiGroup: rbac.authorization.k8s.io

