apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  namespace: nextcloud
spec:
  schedule: "*/5 * * * *"   # Every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cron-runner
            image: nextcloud:latest
            command: 
              - /bin/sh
              - -c
              - |
                su - www-data -s /bin/sh -c 'php -f /var/www/html/cron.php'
            volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
          volumes:
          - name: nextcloud-storage
            persistentVolumeClaim:
              claimName: nextcloud-pvc
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
