apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: your-strong-password # change this!!!
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud-pvc
