apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.8.0
        args:
        - -config.file=/etc/loki/loki-config.yaml
        ports:
        - containerPort: 3100
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        persistentVolumeClaim:
          claimName: loki-pvc
      initContainers:
      - name: init-storage
        image: busybox:1.28
        command: ["sh", "-c", "mkdir -p /loki/chunks /loki/rules /loki/boltdb-shipper-active /loki/boltdb-shipper-cache && chown -R 10001:10001 /loki"]
        volumeMounts:
        - name: storage
          mountPath: /loki
