apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
  namespace: homepage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/homepage-config
