apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-prov
  namespace: telemetry

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: grafana-pv-prov
