apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-prov

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/grafana-provisioning
