apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: telemetry
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"
