apiVersion: v1
kind: PersistentVolume
metadata:
  name: ta-postgres-pv

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/taiga-postgres
