apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-redis
  namespace: taiga

spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: taiga-redis
  template:
    metadata:
      labels:
        app: taiga-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
          - containerPort: 6379
