apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-backend
  namespace: taiga

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: taiga-backend
  template:
    metadata:
      labels:
        app: taiga-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: taiga-backend
        image: taigaio/taiga-back:latest
          # command: ["/bin/sh", "-c", "chown -R taiga:taiga /taiga-back && exec /opt/venv/bin/gunicorn taiga.wsgi --bind 0.0.0.0:8000"]
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: taiga-config
          - secretRef:
              name: postgres-secret
          - secretRef:
              name: taiga-secret
