apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-frontend
  namespace: taiga

spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: taiga-frontend
  template:
    metadata:
      labels:
        app: taiga-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: taiga-frontend
          image: taigaio/taiga-front:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: taiga-config
