apiVersion: v1
kind: ConfigMap
metadata:
  name: taiga-config
  namespace: taiga

data:
  REDIS_URL: "http://taiga-redis.taiga.svc.cluster.local:6379"
  TAIGA_URL: "http://taiga.husamalsheikh.info"
  PUBLIC_REGISTER_ENABLED: "true"
