apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-backend
  namespace: taiga

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: taiga-backend
  template:
    metadata:
      labels:
        app: taiga-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: taiga-backend
        image: taigaio/taiga-back:latest
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
          - containerPort: 8000
        env:
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_HOST
          value: "postgres.taiga.svc.cluster.local"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
          - configMapRef:
              name: taiga-config
