apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commafeed-pvc
  namespace: commafeed

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: commafeed-pv
